import Head from 'next/head'

import { Hero } from '../components/Hero'
import { OurJobs } from '../components/OurJobs'

export default function Home() {

  return (
    <div>
      <Head>
        <title>ARS Engenharia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero
        heading={'ARS Engenharia'}
        message={
          'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Esse fugit, dolorem officiis dolore quae ad inventore voluptate, sed facilis, beatae sunt consequuntur? Animi voluptatibus ducimus, debitis eaque magnam libero modi?'
        }
      />

      <div className='mt-10 max-w-7xl mx-auto'>
        <h1 id="Services" className='mb-6 flex justify-center text-3xl font-bold text-[#18475D]'>Nossos Serviços</h1>
        <OurJobs />
      </div>


      <div>
        Ola
      </div>
    </div>
  )
}
