import Head from 'next/head'

import React from 'react'
import { Hero } from '../components/Hero'

export default function Home() {
  return (
    <div>
      <Head>
        <title>ARS Engenharia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero
        heading={'ARS Engenharia'}
        message={
          'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Esse fugit, dolorem officiis dolore quae ad inventore voluptate, sed facilis, beatae sunt consequuntur? Animi voluptatibus ducimus, debitis eaque magnam libero modi?'
        }
      />
    </div>
  )
}
